language: c

sudo: false

os:
  - linux

compiler:
  - gcc

env:
  global:
    - secure: "GFjrqOUyqNLrPGtxNW4r9JxJBudjddBJFzEEcpPkfEbMHJ+kk4zOYsSLV1f1cAK+X8TWLsCq5Yjt/2Rzhu7Csjiy34RReZ9KwsmcwX78T8MkQQz4yv8by9J9a5mbHQ3S6mtF7PH1t38PKVcJi51icEqUjvi4FnfME5+VrdueE+c="
  matrix:
    - CHECK="normal"

matrix:
  include:
    ## distcheck
    - os: linux
      compiler: gcc
      env: CHECK="distcheck"
    ## Ubuntu 14.04 Trusty (beta), sudo required!
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: TRUSTY="yes" CHECK="normal"
    ## OSX
    - os: osx
      compiler: clang
      env: CHECK="normal"

before_install:
  - if test "$TRUSTY" = "yes"; then
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt;
    fi

before_script:
  - autoreconf -vfi
  - ./configure --enable-contrib

script:
  - if [ "$CHECK" = "normal" ]; then
      ./configure --enable-contrib || { cat config.log; false; } &&
      make -j2 clean && make -j2 check || { cat test/test-suite.log; false; } ;
    fi
  - if [ "$CHECK" = "distcheck" ]; then
      ./configure --enable-tzmap-fetch || { cat config.log; false; } &&
      make -j2 all && make -j1 distcheck;
    fi

after_script:
  # find test log from check as well as from distcheck
  - find -name test-suite.log | xargs -r cat

## whitelist
branches:
  only:
    - coverity-scan
    - /^travis.*/
    - /^tmp.*/
    - /^v\d+\..*/

notifications:
  email:
    - devel@fresse.org

addons:
  apt:
    packages:
      - gperf
      - texinfo
      - bison
      - flex
      - texlive
  coverity_scan:
    project:
      name: "hroptatyr/dateutils"
      description: "dateutils coverity scan"
    notification_email: devel@fresse.org
    build_command_prepend: "./configure"
    build_command: "make all check"
    branch_pattern: coverity-scan

deploy:
  provider: releases
  api_key:
    secure: WRTz8MTXtkK69Hk/E1iXj4wXxko60vXgmcuW0RaLeRpmphUN9emVUu791W7fQeqx4j/GM32vwGPDa0jdm4dQ2s4ptNpEliisOpx/sGwJsugmeQm/5lSwTMuDwSWoIdWV7HRwsaWodXSzrxFBbZ9g+peTjz28geXp7lDtUCQbWC0=
  file_glob: true
  file: dateutils-*.tar.xz
  skip_cleanup: true
  on:
    tags: true
